import type { Beat } from "./types";

/**
 * Illustrated opening then spoken entrance beats.
 * Simon's seatmate unnamed in-post; Kane is likely, not proven.
 * Mikari 16.05/17.05 vs 17.07.2025 unresolved.
 */
export const STORY: Beat[] = [
  {
    id: "open",
    kind: "scene",
    title: "17.07.2025",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-intro-peninsula.png",
    text: "An evening on a peninsula that does not exist on maps, globes, or the internet.",
    next: "intro-trip",
  },
  {
    id: "intro-trip",
    kind: "scene",
    title: "Company vacation",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "A mansion wait at the end of the road. Some paid their own way. Some were delivered. The company has a name it has not given.",
    next: "intro-bus",
  },
  {
    id: "intro-bus",
    kind: "scene",
    title: "20:35",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    text: "One tourist bus. Warm lamps. An unmapped road. Arrival is close enough to taste.",
    next: "intro-pairs",
  },
  {
    id: "intro-pairs",
    kind: "scene",
    title: "Seats in pairs",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-seating-pairs.png",
    sprites: ["mikari", "adena", "simon", "kane"],
    text: "A good hour to introduce yourselves — if anyone will organize it.",
    next: "seat-girls",
  },
  {
    id: "seat-girls",
    kind: "scene",
    title: "Farther row",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-pair-seats.png",
    sprites: ["mikari", "adena"],
    text: "Mikari sat a little apart. Beside her: a red-haired girl, odd-looking — Adena / Deni, lion ears under a hoodie.",
    next: "seat-unfriendly",
  },
  {
    id: "seat-unfriendly",
    kind: "scene",
    title: "Nearer row",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-pair-seats.png",
    sprites: ["simon", "kane"],
    text: "Simon’s seatmate is about his age, and unfriendly. The posts never name that neighbor. Kane Avis sits at a window like that — likely, not proven.",
    next: "kane-enter",
  },
  {
    id: "kane-enter",
    kind: "chat",
    title: "Kane Avis",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "…Too many people. I didn't sign for a crowd. Window. Then a room I can shut. That's the whole itinerary.",
    next: "simon-enter",
  },
  {
    id: "simon-enter",
    kind: "chat",
    title: "Simon Harrison",
    speaker: "simon",
    expression: "neutral",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "I don't… usually leave the house. Something shoved me onto this bus. A few people stand out. The guy next to me looks my age. He does not look friendly. Book first. Arrival later.",
    next: "mikari-enter",
  },
  {
    id: "mikari-enter",
    kind: "chat",
    title: "Mikari / Tsuji",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "“Thanks for listening. See you on site.” That's all they left me. Not one answer. I packed books until the suitcase lost. I read the whole flight instead of sleeping — whose idea was that? Notes on my phone still say 16.05, 17.05. This trip is stamped 17.07.2025. I don't know. Headphones. Sleep. The red-haired girl beside me is strange. I like that.",
    next: "adena-enter",
  },
  {
    id: "adena-enter",
    kind: "chat",
    title: "Adena / Deni",
    speaker: "adena",
    expression: "tired",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "Fields, houses, forest — it all smears. One song in one ear. Headache. Dorm walls got too loud, so I said yes to anywhere-else. They let me bring more than luggage. That's why Laska is here. My seatmate looks about eighteen. Glass is safer than staring.",
    next: "laska-enter",
  },
  {
    id: "laska-enter",
    kind: "chat",
    title: "Laska",
    speaker: "laska",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "laska"],
    text: "*a black nose pokes a pale cheek — yawn, then a tiny huff*",
    next: "adena-whisper",
  },
  {
    id: "adena-whisper",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "It's stuffy for me too. Hold on. We should be there soon.",
    next: "choice-organizer",
  },
  {
    id: "choice-organizer",
    kind: "chat",
    title: "Before the mansion",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprites: ["kane", "simon", "mikari", "adena"],
    text: "Pairs. Warm lamps. Who organizes introductions?",
    choices: [
      {
        id: "org-simon",
        label: "Simon marks his page and tries, softly, to speak for the row.",
        next: "org-simon",
        set: { organizer: "simon" },
      },
      {
        id: "org-adena",
        label: "Adena talks to the glass — and therefore to the cabin — with Laska as cover.",
        next: "org-adena",
        set: { organizer: "adena" },
      },
      {
        id: "org-mikari",
        label: "Mikari yanks an earbud. The company never asked names. She will.",
        next: "org-mikari",
        set: { organizer: "mikari" },
      },
      {
        id: "org-kane",
        label: "A tired sentence from the window. Nobody expected Kane to start.",
        next: "org-kane",
        set: { organizer: "kane" },
      },
      {
        id: "org-none",
        label: "Let the silence stand. Rooms can do the introducing.",
        next: "org-none",
        set: { organizer: "none" },
      },
    ],
  },
  {
    id: "org-simon",
    kind: "chat",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "Before we vanish into rooms — I'm Simon Harrison. That's… that's all I had.",
    next: "org-simon-2",
  },
  {
    id: "org-simon-2",
    kind: "chat",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "…",
    next: "choice-attention",
  },
  {
    id: "org-adena",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "I'm Adena. This is Laska. We can do names without turning around. The glass already has everyone's face.",
    next: "org-adena-2",
  },
  {
    id: "org-adena-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "…Mikari. Don't make it a speech.",
    next: "choice-attention",
  },
  {
    id: "org-mikari",
    kind: "chat",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "Names. Now. I'm Mikari. The company didn't bother. I am not sitting in the dark until a mansion door.",
    next: "org-mikari-2",
  },
  {
    id: "org-mikari-2",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Adena. Laska. Your hair tips — they caught the lamp. That's all I was going to say.",
    next: "choice-attention",
  },
  {
    id: "org-kane",
    kind: "chat",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    sprites: ["kane", "simon"],
    text: "Kane Avis. Don't make it a circle.",
    next: "org-kane-2",
  },
  {
    id: "org-kane-2",
    kind: "chat",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    text: "…Right. Simon. I'll just… keep the page.",
    next: "choice-attention",
  },
  {
    id: "org-none",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    text: "No one claims the job. Headphones. Paper. Glass. The peninsula keeps its secret; so do they.",
    next: "choice-attention",
  },
  {
    id: "choice-attention",
    kind: "chat",
    title: "Where you look",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-window-reflection.png",
    text: "Attention is a choice. The cabin pulls three ways.",
    choices: [
      {
        id: "att-girls",
        label: "Mikari’s headphones. Adena’s lion ears. A weasel in a hoodie.",
        next: "att-girls",
        set: { attention: "pairs-girls" },
      },
      {
        id: "att-unfriendly",
        label: "Simon’s book, and the similar-age unfriendly seatmate — unnamed in that post.",
        next: "att-unfriendly",
        set: { attention: "pairs-unfriendly" },
      },
      {
        id: "att-window",
        label: "The window: cabin ghosts on the glass, road darkness beyond.",
        next: "att-window",
        set: { attention: "window" },
      },
    ],
  },
  {
    id: "att-girls",
    kind: "chat",
    speaker: "adena",
    expression: "neutral",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "Eighteen, maybe. Books in the pack. Orange-red tips. I won't ask why her notes don't match July. People come this far for too many reasons.",
    next: "att-girls-2",
  },
  {
    id: "att-girls-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "If you're talking, do it quieter. I'm trying to sleep through a company that doesn't write back.",
    next: "choice-arrival",
  },
  {
    id: "att-unfriendly",
    kind: "chat",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "Same paragraph, twice. If that's Kane Avis, nobody wrote it down — only the age, and the lack of welcome.",
    next: "att-unfriendly-2",
  },
  {
    id: "att-unfriendly-2",
    kind: "chat",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "Don't invent a conversation. The glass is enough.",
    next: "choice-arrival",
  },
  {
    id: "att-window",
    kind: "chat",
    speaker: "adena",
    expression: "neutral",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "I can look without being caught. Strangers in pairs. A mansion that isn't on any map. Laska is a small heat on my collarbone.",
    next: "choice-arrival",
  },
  {
    id: "choice-arrival",
    kind: "chat",
    title: "Arrival",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Brakes. Warm windows in a dark tree-line. How do you step off?",
    choices: [
      {
        id: "arr-rooms",
        label: "Follow the plan Kane said out loud: a private room, then a closed door.",
        next: "arr-rooms",
        set: { arrival: "rooms" },
      },
      {
        id: "arr-gate",
        label: "Linger at the gate. Names, if any, still hang in the air.",
        next: "arr-gate",
        set: { arrival: "gate" },
      },
      {
        id: "arr-laska",
        label: "Wait with Adena until Laska will walk on gravel.",
        next: "arr-laska",
        set: { arrival: "laska" },
      },
    ],
  },
  {
    id: "arr-rooms",
    kind: "chat",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "kane",
    text: "No circle. No tour. A room was the only promise that mattered.",
    next: "arr-rooms-2",
  },
  {
    id: "arr-rooms-2",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    sprites: ["mikari", "simon", "adena"],
    text: "Behind him the bus empties in pairs. Mikari half-asleep. Simon still holding the book. Adena whispering to a weasel. The peninsula stays unnamed. So does the company.",
    next: "end",
  },
  {
    id: "arr-gate",
    kind: "chat",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "simon",
    text: "I almost say the name again. I don't.",
    next: "arr-gate-2",
  },
  {
    id: "arr-gate-2",
    kind: "chat",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "This building owes me answers. Don't look at me like that's a joke.",
    next: "arr-gate-3",
  },
  {
    id: "arr-gate-3",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Adena's heterochromia catches the porch light. The unfriendly young man from Simon's row is already a silhouette on the path. The mansion does not care who spoke.",
    next: "end",
  },
  {
    id: "arr-laska",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "adena",
    sprites: ["adena", "laska"],
    text: "Night air. Not bus heat. Easy, Laska — gravel is loud if you aren't used to it.",
    next: "arr-laska-2",
  },
  {
    id: "arr-laska-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "mikari",
    text: "…I'm not waiting. I'm just standing. Don't make it a thing.",
    next: "end",
  },
  {
    id: "end",
    kind: "scene",
    title: "Session closed",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Scene 1 complete. Kane Avis, Simon Harrison, Mikari / Tsuji, Adena / Deni, Laska. What the company is, who paid, and why Mikari's dates disagree with July, stay open.",
  },
];

export function beatById(id: string): Beat | undefined {
  return STORY.find((b) => b.id === id);
}
