import type { Beat } from "./types";

/**
 * Scene 1 from player posts: 17.07.2025, unmapped peninsula, tourist bus ~20:35.
 * Seating: Mikari beside a red-haired girl (Adena by description); Simon beside a similar-age unfriendly guy (Kane is likely, not proven in-post).
 * Mikari's private dates 16.05/17.05 vs 17.07.2025 stay unresolved.
 */
export const STORY: Beat[] = [
  {
    id: "open",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-peninsula-road.png",
    text: "17.07.2025. An unknown peninsula — missing from maps, globes, even the internet. Strange, and somehow not worth a question. A tourist bus carries a company vacation toward a mansion. Some paid their own way. Some were delivered. At 20:35 the seats are taken in pairs. Before arrival, someone could still organize introductions.",
    next: "kane-window",
  },
  {
    id: "kane-window",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "Kane Avis looks about twenty-two. Whatever talked him into this trip, he did not bargain for this many people. He keeps his eyes on the glass and waits for a private room he can shut.",
    next: "simon-book",
  },
  {
    id: "simon-book",
    speaker: "simon",
    expression: "neutral",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    text: "Simon Harrison is the type who stays home unless he must. Tonight he is on a bus. A few passengers stand out. His seatmate looks about the same age — and not friendly. The post never names that neighbor. Simon takes a book from his bag and waits.",
    next: "mikari-phones",
  },
  {
    id: "mikari-phones",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "Mikari — Tsuji — still has the company's last recording in her teeth: they answered none of her questions. She packed too many books, flew anyway, failed to sleep. On boarding, the tips of her hair went orange-red. She sat a little apart. Beside her: a red-haired girl, odd-looking, and Mikari liked that. Headphones in. Try to sleep. Her own notes say 16.05 / 17.05. The opening is dated 17.07.2025. Nobody has closed that gap.",
    next: "adena-glass",
  },
  {
    id: "adena-glass",
    speaker: "adena",
    expression: "tired",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Adena — Deni — watches fields, houses, forest, through a stuffy headache and a looping song in one earbud. Right eye black, white broken lines. Left eye red, orange pupil. Lion ears under a black hoodie. From the collar, a white muzzle with a peach diamond: Laska, allowed because the trip permitted more than luggage. The window reflects the cabin full of strangers. Her seatmate looks about eighteen.",
    next: "laska-poke",
  },
  {
    id: "laska-poke",
    speaker: "laska",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Laska yawns and pokes Adena's pale cheek with a black nose. Adena murmurs that it is stuffy for her too — they should arrive soon. The weasel huffs and vanishes into the hoodie.",
    next: "choice-organizer",
  },
  {
    id: "choice-organizer",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    text: "Pairs. Warm lamps. An unmapped road. Who organizes introductions before the mansion?",
    choices: [
      {
        id: "org-simon",
        label: "Simon closes the book and tries to speak for the row.",
        next: "org-simon",
        set: { organizer: "simon" },
      },
      {
        id: "org-adena",
        label: "Adena uses the window-reflection to start — quietly, with Laska as cover.",
        next: "org-adena",
        set: { organizer: "adena" },
      },
      {
        id: "org-mikari",
        label: "Mikari yanks an earbud and demands names because the company never did.",
        next: "org-mikari",
        set: { organizer: "mikari" },
      },
      {
        id: "org-kane",
        label: "Nobody expects Kane — which is why a single tired sentence from the window hits harder.",
        next: "org-kane",
        set: { organizer: "kane" },
      },
      {
        id: "org-none",
        label: "Let the silence stand. Introductions can wait for private rooms.",
        next: "org-none",
        set: { organizer: "none" },
      },
    ],
  },
  {
    id: "org-simon",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    text: "Simon marks his page. \"Before we vanish into rooms — I'm Simon Harrison.\" His voice is too soft for a whole bus. The unfriendly seatmate does not turn. Across the aisle, a few heads do.",
    next: "choice-attention",
  },
  {
    id: "org-adena",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Adena speaks to the glass, which is also the cabin. \"I'm Adena. This is Laska.\" The weasel's face appears like a punctuation mark. Mikari's eye opens a slit. The unfriendly pair up front still pretends the window is more interesting.",
    next: "choice-attention",
  },
  {
    id: "org-mikari",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "\"Names. Now. I'm Mikari. The company didn't bother.\" Books shift in her pack. The red-haired girl beside her almost smiles. Someone in the next pair flinches as if conversation were a personal attack.",
    next: "choice-attention",
  },
  {
    id: "org-kane",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "Kane does not face the aisle. \"Kane Avis. Don't make it a circle.\" That is the whole speech. Simon's book lowers a centimeter. The rest of the bus files the name away like a warning.",
    next: "choice-attention",
  },
  {
    id: "org-none",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    text: "No one claims the job. Headphones, paper, glass. The peninsula keeps its secret; the passengers keep theirs. Introductions remain optional — and undone.",
    next: "choice-attention",
  },
  {
    id: "choice-attention",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-window-reflection.png",
    text: "Attention is a choice too. Where does the cabin pull your eyes?",
    choices: [
      {
        id: "att-girls",
        label: "The farther pair: Mikari with headphones, Adena with lion ears and a weasel in her hoodie.",
        next: "att-girls",
        set: { attention: "pairs-girls" },
      },
      {
        id: "att-unfriendly",
        label: "Simon's row: a book, and a similar-age guy who looks unfriendly (Kane is likely — not named in that post).",
        next: "att-unfriendly",
        set: { attention: "pairs-unfriendly" },
      },
      {
        id: "att-window",
        label: "The window itself — cabin ghosts on the glass, road darkness beyond.",
        next: "att-window",
        set: { attention: "window" },
      },
    ],
  },
  {
    id: "att-girls",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "Mikari's music leaks a thin thread. Adena studies her through the reflection so nobody can accuse her of staring. Eighteen, maybe. Books. Orange-red tips. The lion-eared girl does not ask about the mismatched dates in anyone's notes. She only thinks: people come this far for many reasons.",
    next: "choice-arrival",
  },
  {
    id: "att-unfriendly",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    text: "Simon reads the same paragraph twice. His neighbor's tired gaze is welded to the night. If that is Kane Avis, the posts never say so — only age, and the lack of welcome. The book stays open like a door that is not.",
    next: "choice-arrival",
  },
  {
    id: "att-window",
    speaker: "adena",
    expression: "neutral",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Glass doubles everyone. Adena likes that: you can look without being caught. Strangers stacked in pairs, a mansion somewhere ahead that is not on any map. Laska's breath is a small heat against her collarbone.",
    next: "choice-arrival",
  },
  {
    id: "choice-arrival",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Brakes. Warm windows in a dark tree-line. The mansion, at last. How do you step off?",
    choices: [
      {
        id: "arr-rooms",
        label: "Follow Kane's plan: get to a private room and close it.",
        next: "arr-rooms",
        set: { arrival: "rooms" },
      },
      {
        id: "arr-gate",
        label: "Linger at the gate. Names, if any were spoken, still hang in the air.",
        next: "arr-gate",
        set: { arrival: "gate" },
      },
      {
        id: "arr-laska",
        label: "Wait with Adena until Laska will walk on gravel.",
        next: "arr-laska",
        set: { arrival: "laska" },
      },
    ],
  },
  {
    id: "arr-rooms",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "kane",
    text: "Kane is first off, or close enough. No circle. No tour. A personal room was the only promise that mattered. Behind him the bus empties in pairs — Mikari still half-asleep, Simon still holding the book, Adena whispering to a weasel. The peninsula stays unnamed. So does the company.",
    next: "end",
  },
  {
    id: "arr-gate",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "simon",
    text: "At the iron gate Simon almost repeats his name, then doesn't. Mikari looks at the building like it owes her answers. Adena's heterochromia catches the porch light. The unfriendly young man from Simon's row is already a silhouette on the path. Introductions happened, or they didn't. The mansion does not care.",
    next: "end",
  },
  {
    id: "arr-laska",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "adena",
    text: "Adena sets Laska on her shoulder. Night air instead of bus heat. Mikari waits a second longer than she meant to — the red-haired seatmate was, after all, the one she liked. Kane does not wait. Simon folds a page. Somewhere a private room door will shut. The opening ends here: 20:35 become arrival, and the unmapped peninsula keeps the rest.",
    next: "end",
  },
  {
    id: "end",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Session log closed. Scene 1 — bus to mansion — complete. The four who spoke remain Kane Avis, Simon Harrison, Mikari / Tsuji, Adena / Deni, and Laska. No further mains. What the company is, who paid, and why Mikari's dates disagree with July, stay open.",
  },
];

export function beatById(id: string): Beat | undefined {
  return STORY.find((b) => b.id === id);
}
