import type { Beat } from "./types";

/**
 * Illustrated opening then spoken entrance beats.
 * Simon's seatmate unnamed in-post; Kane is likely, not proven.
 * Mikari 16.05/17.05 vs 17.07.2025 unresolved.
 */
export const STORY: Beat[] = [
  {
    id: "hook-tape",
    kind: "chat",
    title: "20:35 · cabin speaker",
    eta: "20:35",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "“Thanks for listening to this message. See you on site.” — That's the company. That's ALL they left. Not one answer. And they still have a speaker on this bus?",
    next: "hook-choice",
  },
  {
    id: "hook-choice",
    kind: "chat",
    title: "The tape is still playing",
    eta: "20:35",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-seating-pairs.png",
    sprites: ["mikari", "adena", "simon", "kane"],
    text: "Warm lamps. Pairs. A peninsula that isn't on maps. Arrival is close. Who do you lean toward before anyone organizes a thing?",
    choices: [
      {
        id: "hook-tape",
        label: "Stay on Mikari — demand what “on site” even means.",
        next: "hook-mikari",
        set: { hook: "tape", attention: "pairs-girls" },
      },
      {
        id: "hook-window",
        label: "The farther pair: red hair, lion ears, a muzzle in a hoodie.",
        next: "hook-adena",
        set: { hook: "window", attention: "pairs-girls" },
      },
      {
        id: "hook-book",
        label: "The nearer pair: a book, and a similar-age guy who does not look friendly.",
        next: "hook-simon",
        set: { hook: "book", attention: "pairs-unfriendly" },
      },
    ],
  },
  {
    id: "hook-mikari",
    kind: "chat",
    eta: "20:36",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "Don't look at me like I have a brochure. I packed books until the suitcase lost. I read the whole flight. My notes still say 16.05, 17.05 — this stamp is 17.07.2025. Nobody closed that. Headphones. Sleep. The red-haired girl beside me is strange. I like that more than the speaker.",
    next: "hook-surprise",
  },
  {
    id: "hook-adena",
    kind: "chat",
    eta: "20:36",
    speaker: "adena",
    expression: "tired",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "One song. One ear. Headache. I said yes because the dorm walls were louder than this. They let me bring more than luggage — that's Laska. Glass is safer than staring. My seatmate looks about eighteen. If that speaker is a welcome, it's a bad one.",
    next: "hook-surprise",
  },
  {
    id: "hook-simon",
    kind: "chat",
    eta: "20:36",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "I don't usually leave the house. Something shoved me onto this bus. A few people stand out. The guy next to me looks my age. He does not look friendly — nobody wrote his name down. Book first. If that's Kane Avis at the glass, that's a guess, not a fact.",
    next: "hook-surprise",
  },
  {
    id: "hook-surprise",
    kind: "chat",
    title: "The window speaks first",
    eta: "20:36",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    sprites: ["kane", "simon"],
    text: "If that recording is a welcome, it isn't. Kane Avis. Don't make it a circle. I want a room I can shut. That's the itinerary.",
    next: "hook-laska",
  },
  {
    id: "hook-laska",
    kind: "chat",
    eta: "20:36",
    speaker: "laska",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "laska"],
    text: "*a black nose punches a pale cheek from inside a hoodie — yawn, then a tiny furious huff*",
    next: "adena-whisper",
  },
  {
    id: "adena-whisper",
    kind: "chat",
    eta: "20:36",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "It's stuffy for me too. Hold on. We should be there soon. …I'm Adena. This is Laska. If anyone still wants names before the mansion — that's on you.",
    next: "choice-organizer",
  },
  {
    id: "choice-organizer",
    kind: "chat",
    title: "Before the mansion",
    eta: "20:37",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprites: ["kane", "simon", "mikari", "adena"],
    text: "Pairs. Warm lamps. Who organizes introductions?",
    choices: [
      {
        id: "org-simon",
        label: "Simon marks his page and tries, softly, to speak for the row.",
        next: "org-simon",
        set: { organizer: "simon" },
      },
      {
        id: "org-adena",
        label: "Adena talks to the glass — and therefore to the cabin — with Laska as cover.",
        next: "org-adena",
        set: { organizer: "adena" },
      },
      {
        id: "org-mikari",
        label: "Mikari yanks an earbud. The company never asked names. She will.",
        next: "org-mikari",
        set: { organizer: "mikari" },
      },
      {
        id: "org-kane",
        label: "A tired sentence from the window. Nobody expected Kane to start.",
        next: "org-kane",
        set: { organizer: "kane" },
      },
      {
        id: "org-none",
        label: "Let the silence stand. Rooms can do the introducing.",
        next: "org-none",
        set: { organizer: "none" },
      },
    ],
  },
  {
    id: "org-simon",
    kind: "chat",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "Before we vanish into rooms — I'm Simon Harrison. That's… that's all I had.",
    next: "org-simon-2",
  },
  {
    id: "org-simon-2",
    kind: "chat",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "…",
    next: "choice-attention",
  },
  {
    id: "org-adena",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "I'm Adena. This is Laska. We can do names without turning around. The glass already has everyone's face.",
    next: "org-adena-2",
  },
  {
    id: "org-adena-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "…Mikari. Don't make it a speech.",
    next: "choice-attention",
  },
  {
    id: "org-mikari",
    kind: "chat",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "Names. Now. I'm Mikari. The company didn't bother. I am not sitting in the dark until a mansion door.",
    next: "org-mikari-2",
  },
  {
    id: "org-mikari-2",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "Adena. Laska. Your hair tips — they caught the lamp. That's all I was going to say.",
    next: "choice-attention",
  },
  {
    id: "org-kane",
    kind: "chat",
    speaker: "kane",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    sprites: ["kane", "simon"],
    text: "Kane Avis. Don't make it a circle.",
    next: "org-kane-2",
  },
  {
    id: "org-kane-2",
    kind: "chat",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    text: "…Right. Simon. I'll just… keep the page.",
    next: "choice-attention",
  },
  {
    id: "org-none",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    text: "No one claims the job. Headphones. Paper. Glass. The peninsula keeps its secret; so do they.",
    next: "choice-attention",
  },
  {
    id: "choice-attention",
    kind: "chat",
    title: "Where you look",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-window-reflection.png",
    text: "Attention is a choice. The cabin pulls three ways.",
    choices: [
      {
        id: "att-girls",
        label: "Mikari’s headphones. Adena’s lion ears. A weasel in a hoodie.",
        next: "att-girls",
        set: { attention: "pairs-girls" },
      },
      {
        id: "att-unfriendly",
        label: "Simon’s book, and the similar-age unfriendly seatmate — unnamed in that post.",
        next: "att-unfriendly",
        set: { attention: "pairs-unfriendly" },
      },
      {
        id: "att-window",
        label: "The window: cabin ghosts on the glass, road darkness beyond.",
        next: "att-window",
        set: { attention: "window" },
      },
    ],
  },
  {
    id: "att-girls",
    kind: "chat",
    speaker: "adena",
    expression: "neutral",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "adena",
    sprites: ["adena", "mikari"],
    text: "Eighteen, maybe. Books in the pack. Orange-red tips. I won't ask why her notes don't match July. People come this far for too many reasons.",
    next: "att-girls-2",
  },
  {
    id: "att-girls-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "mikari",
    text: "If you're talking, do it quieter. I'm trying to sleep through a company that doesn't write back.",
    next: "choice-arrival",
  },
  {
    id: "att-unfriendly",
    kind: "chat",
    speaker: "simon",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "simon",
    sprites: ["simon", "kane"],
    text: "Same paragraph, twice. If that's Kane Avis, nobody wrote it down — only the age, and the lack of welcome.",
    next: "att-unfriendly-2",
  },
  {
    id: "att-unfriendly-2",
    kind: "chat",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-bus-dusk.png",
    sprite: "kane",
    text: "Don't invent a conversation. The glass is enough.",
    next: "choice-arrival",
  },
  {
    id: "att-window",
    kind: "chat",
    speaker: "adena",
    expression: "neutral",
    bg: "assets/backgrounds/bg-window-reflection.png",
    sprite: "adena",
    text: "I can look without being caught. Strangers in pairs. A mansion that isn't on any map. Laska is a small heat on my collarbone.",
    next: "choice-arrival",
  },
  {
    id: "choice-arrival",
    kind: "chat",
    title: "Arrival",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Brakes. Warm windows in a dark tree-line. How do you step off?",
    choices: [
      {
        id: "arr-rooms",
        label: "Follow the plan Kane said out loud: a private room, then a closed door.",
        next: "arr-rooms",
        set: { arrival: "rooms" },
      },
      {
        id: "arr-gate",
        label: "Linger at the gate. Names, if any, still hang in the air.",
        next: "arr-gate",
        set: { arrival: "gate" },
      },
      {
        id: "arr-laska",
        label: "Wait with Adena until Laska will walk on gravel.",
        next: "arr-laska",
        set: { arrival: "laska" },
      },
    ],
  },
  {
    id: "arr-rooms",
    kind: "chat",
    speaker: "kane",
    expression: "tired",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "kane",
    text: "No circle. No tour. A room was the only promise that mattered.",
    next: "arr-rooms-2",
  },
  {
    id: "arr-rooms-2",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    sprites: ["mikari", "simon", "adena"],
    text: "Behind him the bus empties in pairs. Mikari half-asleep. Simon still holding the book. Adena whispering to a weasel. The peninsula stays unnamed. So does the company.",
    next: "end",
  },
  {
    id: "arr-gate",
    kind: "chat",
    speaker: "simon",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "simon",
    text: "I almost say the name again. I don't.",
    next: "arr-gate-2",
  },
  {
    id: "arr-gate-2",
    kind: "chat",
    speaker: "mikari",
    expression: "annoyed",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "mikari",
    sprites: ["mikari", "adena"],
    text: "This building owes me answers. Don't look at me like that's a joke.",
    next: "arr-gate-3",
  },
  {
    id: "arr-gate-3",
    kind: "chat",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Adena's heterochromia catches the porch light. The unfriendly young man from Simon's row is already a silhouette on the path. The mansion does not care who spoke.",
    next: "end",
  },
  {
    id: "arr-laska",
    kind: "chat",
    speaker: "adena",
    expression: "smile",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "adena",
    sprites: ["adena", "laska"],
    text: "Night air. Not bus heat. Easy, Laska — gravel is loud if you aren't used to it.",
    next: "arr-laska-2",
  },
  {
    id: "arr-laska-2",
    kind: "chat",
    speaker: "mikari",
    expression: "tired",
    bg: "assets/backgrounds/bg-mansion.png",
    sprite: "mikari",
    text: "…I'm not waiting. I'm just standing. Don't make it a thing.",
    next: "end",
  },
  {
    id: "end",
    kind: "scene",
    title: "Session closed",
    speaker: "narrator",
    bg: "assets/backgrounds/bg-mansion.png",
    text: "Scene 1 complete. Kane Avis, Simon Harrison, Mikari / Tsuji, Adena / Deni, Laska. What the company is, who paid, and why Mikari's dates disagree with July, stay open.",
  },
];

export function beatById(id: string): Beat | undefined {
  return STORY.find((b) => b.id === id);
}
